### ISSUE TITLE
An empty line suggested before return

### ISSUE THREAD

**Issue by Jasminehyz** [Gbuomprisco/opinionated-angular#2]
Hi, I read your blog in medium . It's cool. This is an advice for style guide: An empty line shoud be added before function's return,  like this in a service file:
```
getUsersInAdministration (){
  const requestUrl = 'xxx';

  return this.http.get(requestUrl)
}
       
```
This way may helps with readability.

**Comment by Gbuomprisco** [comment]
I totally agree with this one :) Will add!
